export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Zaufany zespół developerów',
    headline: 'W naszym zespole przykładamy ogromną wagę do relacji między nami.',
    description: 'Wierzymy, że w ten sposób zwiększymy naszą produktywność',
    buttonLabel: 'Dołącz do nas!',
    imgStart: true,
    img: 'https://cdn.discordapp.com/attachments/542032448037584907/770394363247198208/svg-1.svg',
    alt: 'cipowita',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Gwarancja rozwoju serwera',
    headline: 'Jeżeli zdecydujesz, się na użycie naszego bota reklamowego - Gwarantujemy Ci, że Twój serwer wzniesie się na wyżyny 🧡',
    description: 'Zdecydowałeś się?',
    buttonLabel: 'Zaproś bota.',
    imgStart: false,
    img: 'https://cdn.discordapp.com/attachments/542032448037584907/770558579991642112/undraw_stepping_up_g6oo.svg',
    alt: 'cipowita2',
    dark: true,
    primary: true,
    darkText: false,
    ZaprosPrzyciskText: "Zaproś Bota",
    akcjaButton: "https://redirect.rubybot.pl/zaproszenie/"
}


export const homeObjThree = {
    id: 'services',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'gwarancja bezpieczeństwa',
    headline: 'Twoje reklamy i statystyki są zawsze bezpieczne, dzięki autorskim systemom szyfrującym.',
    description: 'Wszystko co tworzymy jest w pełni autorskie.',
    buttonLabel: 'Dowiedz się więcej',
    imgStart: false,
    img: 'https://cdn.discordapp.com/attachments/765188028406562820/770589213246488596/undraw_security_o890.svg',
    alt: 'cipowita',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjFour = {
    id: 'stats',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Statystyki bota',
    headline: 'Zrobiliśmy autorski system statystyk bota.',
    description: 'Nie wierzysz?',
    buttonLabel: 'Sprawdź sam!',
    imgStart: true,
    img: 'https://cdn.discordapp.com/attachments/542032448037584907/770559339030642688/undraw_site_stats_l57q.svg',
    alt: 'cipowita',
    dark: true,
    primary: true,
    darkText: false,
}